### ISSUE TITLE
h1和h4标签可否换成p标签？

### ISSUE THREAD

**Issue by Nickeysoft** [mayuko2012/hexo-tag-mtime#1]
h1和h4标签在NexT样式中与生成目录的标签冲突了

**Comment by Nickeysoft** [comment]
想了一下，觉得span标签不恰当，还是P标签比较合适😁

**Comment by liopoos** [comment]
设置成h1的由衷是想和主题的字体可以更和谐一下，如果需要修改可以修改插件`index.js`文件中的`util.htmlTag('h1', {}, res.name) + util.htmlTag('h4', {}, res.year + '，' + res.director)`h1和h4字段😁

**Comment by Nickeysoft** [comment]
> 设置成h1的由衷是想和主题的字体可以更和谐一下，如果需要修改可以修改插件`index.js`文件中的`util.htmlTag('h1', {}, res.name) + util.htmlTag('h4', {}, res.year + '，' + res.director)`h1和h4字段😁

哈哈，好的，我自己已经改了。

**Comment by liopoos** [comment]
> > 设置成h1的由衷是想和主题的字体可以更和谐一下，如果需要修改可以修改插件`index.js`文件中的`util.htmlTag('h1', {}, res.name) + util.htmlTag('h4', {}, res.year + '，' + res.director)`h1和h4字段😁
> 
> 哈哈，好的，我自己已经改了。

好的👌
