### ISSUE TITLE
很漂亮

### ISSUE THREAD

**Issue by GuoRan18** [mayuko2012/hexo-tag-mtime#2]
之前用过，后来博客换成hugo，忘记插件名字了，好了好久没找到。今天找到了。

**Comment by liopoos** [comment]
> 之前用过，后来博客换成hugo，忘记插件名字了，好了好久没找到。今天找到了。

谢谢支持😁

**Comment by GuoRan18** [comment]
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Template render error: (unknown path)
StatusCodeError: 404 - "404 page not found\n"

hexo g后出现的，之前一直正常，突然就这样了。请教这是什么情况？

**Comment by liopoos** [comment]
你好，是时光网修改了api接口导致查询失败。

**Comment by liopoos** [comment]
#3 已修改API，目前可以正常使用了！
